// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _webApiKey = String.fromEnvironment(
    'FIREBASE_WEB_API_KEY',
  );
  static const String _androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
  );
  static const String _iosApiKey = String.fromEnvironment(
    'FIREBASE_IOS_API_KEY',
  );
  static const String _macosApiKey = String.fromEnvironment(
    'FIREBASE_MACOS_API_KEY',
  );
  static const String _windowsApiKey = String.fromEnvironment(
    'FIREBASE_WINDOWS_API_KEY',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:1004386639130:web:d9b059a205159a8f27a0a3',
    messagingSenderId: '1004386639130',
    projectId: 'wilapp-auth-project',
    authDomain: 'wilapp-auth-project.firebaseapp.com',
    storageBucket: 'wilapp-auth-project.firebasestorage.app',
    measurementId: 'G-HEFFGR02MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _androidApiKey,
    appId: '1:1004386639130:android:19e336f4fc30f82027a0a3',
    messagingSenderId: '1004386639130',
    projectId: 'wilapp-auth-project',
    storageBucket: 'wilapp-auth-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:1004386639130:ios:1d62a79365b1d2db27a0a3',
    messagingSenderId: '1004386639130',
    projectId: 'wilapp-auth-project',
    storageBucket: 'wilapp-auth-project.firebasestorage.app',
    iosBundleId: 'com.example.wilapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _macosApiKey,
    appId: '1:1004386639130:ios:1d62a79365b1d2db27a0a3',
    messagingSenderId: '1004386639130',
    projectId: 'wilapp-auth-project',
    storageBucket: 'wilapp-auth-project.firebasestorage.app',
    iosBundleId: 'com.example.wilapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _windowsApiKey,
    appId: '1:1004386639130:web:bb84c9b2df00474427a0a3',
    messagingSenderId: '1004386639130',
    projectId: 'wilapp-auth-project',
    authDomain: 'wilapp-auth-project.firebaseapp.com',
    storageBucket: 'wilapp-auth-project.firebasestorage.app',
    measurementId: 'G-DGF992V8VX',
  );
}
